### ISSUE TITLE
Pianoroll (mis)labelling.

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#376]
As reported in issue #372, the note labels on the virtual keyboard are 1 octave low. That is C4 is labelled as C3 etc. However the recorded and play back notes are correct.

Regards,
Chris.

**Comment by danvd** [comment]
Hi @therealkitman ,

Issue fixed in master branch. Can you recheck now?

**Comment by therealkitman** [comment]
Hi Andrew,

I downloaded the master zip and rebuilt and ran from ../build/muse/muse2. Problem still exists that the pianoroll note labels are still 1 octave down.

Regards,
Chris.


 
![muse](https://cloud.githubusercontent.com/assets/14888092/10421344/1d34b8f6-70d9-11e5-8cdf-d9dadd4441a9.png)

**Comment by danvd** [comment]
Hi Chris,

Can you run 'make install' before checking? muse's binary use -rpath to hardcode paths to libraries, so when running from build folder it can use old shared libs from previous installation.

I also attached screenshot with current changes.

Regards,
Andrew
![muse_pianoroll_labels](https://cloud.githubusercontent.com/assets/5666218/10421671/5b4fd518-70b5-11e5-8890-266b6d581d39.png)

**Comment by therealkitman** [comment]
Hi Andrew,

All good now. The labels on my pianoroll record and play the right notes.

Thanks very much,
Chris.

**Comment by therealkitman** [comment]
Once comment - the (new?) CPU(%) display is hovering ~30% even though nothing is playing yet my laptop's system monitor is registering ~5%.

**Comment by danvd** [comment]
I changed cpu measuring algorythm some time ago - now it does not use jack api, but calculates cpu usage on it's own. I did not made deep tests, but it can be buggy now :)

**Comment by therealkitman** [comment]
Yeah, not a big concern. It displays ~40% when playing yet the laptops shows 7%.

Thanks again.
