### ISSUE TITLE
Missing '#include <QPainterPath>' statements in awl/knob.h and awl/slider.cpp

### ISSUE THREAD

**Issue by yurivict** [muse-sequencer/muse#838]
```QPainterPath``` is used in these modules without ```#include <QPainterPath>```.

**Comment by terminator356** [comment]
Hello again. This was fixed on 07.06 in the ChangeLog entry "Fixed Qt 5.14/5.15 deprecations".
Luckily, today we put out a new release. Give it a try.

**Comment by yurivict** [comment]
3.1.1 has it fixed in other files, but not in these two.

**Comment by terminator356** [comment]
I checked our source tree and the release file, it is there.
It is in knob.h and slider.h
Still getting an error? I am running Qt 5.15 here and there's no trouble...

**Comment by spamatica** [comment]
Something weird going on here, are you sure you have 3.1.1, and if so,
where did you download it?

I have to concur with Tim, it looks to be there (I don't have qt5.15 so I
can't check the compilation).
I downloaded the 3.1.1 tarball from github and awl/knob.h contains these
lines:

#ifndef __AWLKNOB_H__
#define __AWLKNOB_H__

#include <QPainterPath>
#include <QPaintEvent>


Den mån 20 juli 2020 kl 17:30 skrev yuri@FreeBSD <notifications@github.com>:

**Comment by yurivict** [comment]
My bad. ```awl/knob.h``` has this include, but ```awl/slider.cpp``` doesn't in 3.1.1

**Comment by spamatica** [comment]
It is true that is not defined in awl/slider.cpp, but it is defined in awl/slider.h and should thus be resolved.
We do however have another slider.h file in muse/components/slider.h which does not have any QPainterPath, could it be that the include paths cause it to include the wrong slider.h?

I see you have FreeBSD in your name, just curious, does MusE generally compile on FreeBSD?

**Comment by terminator356** [comment]
Yeah that's a possibility. I saw similar mixups a few times with other headers, here on Linux.

I recall he is the creator/maintainer of the very first package (ports) of MusE for freeBSD.
I helped him get to that point with some fixes. He said it ran. So we know it IS possible...

**Comment by yurivict** [comment]
It builds on FreeBSD. I was going through port patches and found that missing includes that were in patches were resolved upstream, except for this one.

**Comment by kybos** [comment]
The problem is not reproducible here either, but I tried to fix it anyway (current master). Please check if it works for you now.

**Comment by yurivict** [comment]
Thanks!
